### ISSUE TITLE
SyntaxError: The requested module 'react' does not provide an export named 'useCallback'

### ISSUE THREAD

**Issue by soasada** [tailwindlabs/headlessui#1293]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

`^1.5.0`

**What browser are you using?**

Firefox 98.0.2

**Reproduction URL**

https://github.com/soasada/nextjs-tailwindcss-example

**Describe your issue**

When I literally copy and paste the Popover component in a fresh project with: Next.js 12.1.4, React 18 (and also 17), Typescript 4.6.3, starts failing with the following error:

`SyntaxError: The requested module 'react' does not provide an export named 'useCallback'`

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The repo you linked doesn't give any errors for me, so my guess is that your caches are a bit broken.
<img width="211" alt="image" src="https://user-images.githubusercontent.com/1834413/161139855-146d45c6-dc6c-40bc-b575-f242fd6ea101.png">


Try this: `rm -rf .next node_modules && npm install`. This should fix it 👍

**Comment by soasada** [comment]
I have removed the cache before posting the issue and the problem persists, any idea of what could happen?

**Comment by soasada** [comment]
Ok shame on me, I was using node version 12.x apologise for the noise 🙏

**Comment by nckhell** [comment]
Hi @soasada,

I'm having the same issue. What did you do exactly to resolve the issue?

**Comment by soasada** [comment]
What node version are you using? I have updated my node version from 12.x to 16.x and `rm -rf .next node_modules && npm install`, after all of that everything back to normal.

**Comment by nckhell** [comment]
Aha, clear! That did the trick idd, thanks!

**Comment by ian** [comment]
I am having the same issue deploying to Cloudflare Pages. Reverting from 1.5.0 -> 1.4.3 fixes the issue.
