### ISSUE TITLE
Bug: Dialog and TransitionRoot is not working as documented

### ISSUE THREAD

**Issue by albertpratomo** [tailwindlabs/headlessui#959]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.4.2

**What browser are you using?**

Chrome

**Reproduction URL**

```
<template>
  <!--
    Use the TransitionRoot component to add transitions. Use the appear prop
    to animate your dialog on initial render.
  -->
  <TransitionRoot
    appear
    :show="isOpen"
    enter="duration-300 ease-out"
    enter-from="opacity-0"
    enter-to="opacity-100"
    entered="TRANSITION-ROOT-ENTERED"
    leave="duration-200 ease-in"
    leave-from="opacity-100"
    leave-to="opacity-0"
  >
    <!--
      Add `@close` to your Dialog.
    -->
    <Dialog @close="setIsOpen">
      <DialogOverlay />
      <DialogTitle>Deactivate account</DialogTitle>
      <!-- ... -->
      <button @click="isOpen = false">Close</button>
    </Dialog>
  </TransitionRoot>
</template>
```

**Describe your issue**

The code snippet above is copied from the [headlessui dialog doc](https://headlessui.dev/vue/dialog#transitions), and it's not working as expected. The dialog is not transitioning. I suspect it's because the dialog is portaled away, while `<transition-root>` itself is not.

See css class `TRANSITION-ROOT-ENTERED` is still being rendered in the original place rather than portaled away.
![image](https://user-images.githubusercontent.com/25815584/143445783-6ea7d868-e6e8-4419-869a-8c4196b35f47.png)

**Comment by albertpratomo** [comment]
For temporary solution I'm using the Vue built-in `<transition>` component:

```
<dialog
        :open="true"
        :unmount="false"
        @close="closeModal"
    >
        <transition name="fade">
            <div
                v-if="modelValue"
                class="fixed inset-0 z-10"
            >
                <!-- Page Overlay -->
                <dialog-overlay class="fixed inset-0 bg-black opacity-30" />

                <!-- Main Modal -->
                <div
                    class="overflow-hidden rounded inset-center bg-white-off"
                    :class="$attrs.class"
                    :style="$attrs.style"
                >
                    <!-- Close Button -->
                    <button
                        class="absolute p-0 btn-blue-dark top-11 right-11 w-11 h-11"
                        @click="closeModal"
                    >
                        <i-cancel class="w-5 h-5 inset-center" />
                    </button>

                    <slot />
                </div>
            </div>
        </transition>
    </dialog>
```

**Comment by mariatryta** [comment]
Same issue for me. Would be great to find some fix for this 👍

**Comment by sunscreem** [comment]
Yeah - I think I'm having the same problem as well. Wondering how to create a codepen to show it off?

**Comment by rub1e** [comment]
I had the same problem in React, which I fixed by setting the `as` prop on the Transition to a React `Fragment` - that way the div isn't rendered in the original place. I think you have something similar in Vue 3, but I don't really know Vue.

**Comment by MikealGo** [comment]
The way I fixed it is by having a `TransitionChild` and rendering it as a `div`.

**Comment by jiblett1000** [comment]
Same issue here. Using Nuxt 3(Vue 3)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is a documentation issue. You can solve it by doing this (only highlighting the relevant parts here):

```vue
<template>
  <!--
    Use the TransitionRoot component to add transitions. Use the appear prop
    to animate your dialog on initial render.
  -->
  <TransitionRoot
    as="template"
  >
    <Dialog @close="setIsOpen">
      <!-- ... -->
    </Dialog>
  </TransitionRoot>
</template>
```

Notice the 2 `as="..."` calls. What happens is that the `Transition` by default renders a div, the `Dialog` is portalled away. Instead you can tell the transition component to render as a template, which forwards the necessary props to the first child inside (in this case the Dialog).

**Comment by jiblett1000** [comment]
Thanks @RobinMalfait . Maybe I'm misunderstanding your answer, but that it still not working for me. I've created a minimal reproduction here.

https://github.com/jiblett1000/headless-test

**Comment by jiblett1000** [comment]
bump

**Comment by msdrigg** [comment]
Also not working for me -- The default modal doesn't appear when rendered in react

**Comment by msdrigg** [comment]
Nevermind, this was resolved for me in [1326](https://github.com/tailwindlabs/headlessui/pull/1326)

**Comment by jiblett1000** [comment]
Tried with using the insiders version (vue) to see if that resolved it for me as well. Unfortunately, if it is fixed, I can't tell because it now won't allow me to close the dialog.

**Comment by Ashrakk** [comment]
bump
